### ISSUE TITLE
Maven cannot find spring-eg-content-commons

### ISSUE THREAD

**Issue by BillBrower** [paulcwarren/spring-content#35]
I'm following the examples for Spring Content Rest and Maven downloads `spring-content-fs-boot-starter` and `spring-content-rest-boot-starter` just fine but it cannot find version `0.0.1-SNAPSHOT` of `spring-eg-content-commons` [1] Could you upload it to the Central Repository?

[1] https://search.maven.org/#search%7Cga%7C1%7Cspring-eg-content-commons

**Comment by paulcwarren** [comment]
Hi Bill, thanks for giving spring content a try and thanks for the issue.  We don't want to publish that parent POM to maven central so we replaced it with the standard spring-boot parent and properties. 

You should be good now.  

Just FYI.  We are just about to publish a few more getting-started guides to demonstrate our renditions and fulltext search capabilities as well as show how integrations with AWS's NLP services are possible to help to categorize documents and improve search results even further.  Stay tuned!

Anyways, let me know if this fixes your issue and we will close.

**Comment by BillBrower** [comment]
Hi Paul, thanks for getting back to me so fast! Where did you change it? I looked at the samples again but the last change was four days ago.

**Comment by paulcwarren** [comment]
That hateoas error looks familiar and was due to different spring-boot versions.  i.e. spring-content compiled against one version and the application using it spring-content trying to use another version.  In my case though it was spring-content compiled against spring-boot 2 and the application using it attempting to use spring-boot 1.5.x.  

The getting started guides should now be fixed.  If you `git pull` the `gettingstarted-spring-content` repo you should see the references to `spring-eg-content-commons` are now gone.   Those changes are mirrored on the web too.

Let me know if you are still having an issue.  Perhaps we can jump on slack or something?

**Comment by BillBrower** [comment]
I bet it is a version mismatch. We're on spring-boot `2.0.1.RELEASE`. I'd happy to jump on slack! Is there a dedicated slack for the project?

**Comment by paulcwarren** [comment]
There is.  It is `spring-content` on cloudfoundry's slack.  You can come and find us there.  

But it is almost certainly that.  The next release that is currently on master 0.1.0-SNAPSHOT will be our first 2.0 release.  Should be out end of this week, or next.

**Comment by BillBrower** [comment]
Awesome, I'll upgrade when the next release comes out and let you know if I'm still having issues. Thanks Paul!
